/**
 * Single source of truth for the SQLite schema.
 *
 * Kept free of `server-only` so CLI scripts (create-user, migrations) can
 * import it outside a Next.js request context.
 *
 * The better-auth section is generated: run `npm run gen-auth-schema` after
 * upgrading better-auth and paste the output below.
 */
export const SCHEMA_DDL = `

    -- ---------------------------------------------------------------------
    -- better-auth core
    -- Generated by scripts/gen-auth-schema.ts -- do not edit by hand.
    -- Run: npm run gen-auth-schema  (after upgrading better-auth)
    -- ---------------------------------------------------------------------
    CREATE TABLE IF NOT EXISTS "user" (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      emailVerified INTEGER NOT NULL DEFAULT 0,
      image TEXT,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL,
      twoFactorEnabled INTEGER DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS "session" (
      id TEXT PRIMARY KEY NOT NULL,
      expiresAt INTEGER NOT NULL,
      token TEXT NOT NULL UNIQUE,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL,
      ipAddress TEXT,
      userAgent TEXT,
      userId TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "account" (
      id TEXT PRIMARY KEY NOT NULL,
      accountId TEXT NOT NULL,
      providerId TEXT NOT NULL,
      userId TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      accessToken TEXT,
      refreshToken TEXT,
      idToken TEXT,
      accessTokenExpiresAt INTEGER,
      refreshTokenExpiresAt INTEGER,
      scope TEXT,
      password TEXT,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "verification" (
      id TEXT PRIMARY KEY NOT NULL,
      identifier TEXT NOT NULL,
      value TEXT NOT NULL,
      expiresAt INTEGER NOT NULL,
      createdAt INTEGER NOT NULL,
      updatedAt INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "twoFactor" (
      id TEXT PRIMARY KEY NOT NULL,
      secret TEXT NOT NULL,
      backupCodes TEXT NOT NULL,
      userId TEXT NOT NULL REFERENCES "user"(id),
      verified INTEGER DEFAULT 0,
      failedVerificationCount INTEGER,
      lockedUntil INTEGER
    );

    CREATE TABLE IF NOT EXISTS "rateLimit" (
      id TEXT PRIMARY KEY NOT NULL,
      key TEXT NOT NULL UNIQUE,
      count INTEGER NOT NULL,
      lastRequest INTEGER NOT NULL
    );

    -- ---------------------------------------------------------------------
    -- LLMinfo domain tables
    -- ---------------------------------------------------------------------
    CREATE TABLE IF NOT EXISTS providers (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      npm TEXT NOT NULL,
      api TEXT,
      doc TEXT NOT NULL,
      env TEXT NOT NULL,
      has_logo INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS models (
      model_id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL,
      family TEXT,
      offer_count INTEGER NOT NULL DEFAULT 0,
      best_input_price REAL,
      best_output_price REAL,
      best_provider_id TEXT,
      max_context INTEGER,
      min_context INTEGER,
      has_free INTEGER NOT NULL DEFAULT 0,
      has_unpriced INTEGER NOT NULL DEFAULT 0,
      open_weights INTEGER NOT NULL DEFAULT 0,
      reasoning INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS models_family_idx ON models (family);

    CREATE TABLE IF NOT EXISTS offers (
      provider_id TEXT NOT NULL,
      model_id TEXT NOT NULL,
      name TEXT NOT NULL,
      family TEXT,
      description TEXT NOT NULL DEFAULT '',
      attachment INTEGER NOT NULL DEFAULT 0,
      reasoning INTEGER NOT NULL DEFAULT 0,
      reasoning_options TEXT NOT NULL DEFAULT '[]',
      tool_call INTEGER NOT NULL DEFAULT 0,
      structured_output INTEGER NOT NULL DEFAULT 0,
      temperature INTEGER NOT NULL DEFAULT 0,
      interleaved INTEGER NOT NULL DEFAULT 0,
      open_weights INTEGER NOT NULL DEFAULT 0,
      knowledge TEXT,
      release_date TEXT,
      last_updated TEXT,
      status TEXT,
      experimental INTEGER NOT NULL DEFAULT 0,
      input_modalities TEXT NOT NULL DEFAULT '[]',
      output_modalities TEXT NOT NULL DEFAULT '[]',
      context_limit INTEGER,
      input_limit INTEGER,
      output_limit INTEGER,
      cost_input REAL,
      cost_output REAL,
      cost_cache_read REAL,
      cost_cache_write REAL,
      cost_reasoning REAL,
      cost_input_audio REAL,
      cost_output_audio REAL,
      cost_tiers TEXT,
      cost_over_200k TEXT,
      has_cost INTEGER NOT NULL DEFAULT 0,
      is_free INTEGER NOT NULL DEFAULT 0,
      has_tiered_pricing INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (provider_id, model_id)
    );
    CREATE INDEX IF NOT EXISTS offers_model_idx ON offers (model_id);
    CREATE INDEX IF NOT EXISTS offers_provider_idx ON offers (provider_id);

    CREATE TABLE IF NOT EXISTS sync_state (
      id INTEGER PRIMARY KEY DEFAULT 1,
      etag TEXT,
      content_hash TEXT,
      last_synced_at INTEGER,
      last_checked_at INTEGER,
      last_error TEXT,
      provider_count INTEGER NOT NULL DEFAULT 0,
      model_count INTEGER NOT NULL DEFAULT 0,
      offer_count INTEGER NOT NULL DEFAULT 0,
      locked_at INTEGER
    );

    CREATE TABLE IF NOT EXISTS favorites (
      user_id TEXT NOT NULL,
      model_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      PRIMARY KEY (user_id, model_id)
    );

    CREATE TABLE IF NOT EXISTS saved_views (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      query TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS saved_views_user_idx ON saved_views (user_id);

    CREATE TABLE IF NOT EXISTS rate_limits (
      key TEXT PRIMARY KEY,
      count INTEGER NOT NULL DEFAULT 0,
      expires_at INTEGER NOT NULL
    );
`;

/** Statements are idempotent, so applying this on every boot is safe. */
export function applySchema(db: { exec: (sql: string) => unknown }): void {
  db.exec(SCHEMA_DDL);
}
