/**
 * Generates the SQLite DDL for better-auth's own tables.
 *
 * Hand-writing this schema is what caused the first "Failed to initialize
 * database adapter" failure, so it is derived from better-auth's own table
 * definitions instead. Run `npm run gen-auth-schema` after upgrading
 * better-auth and commit the regenerated output.
 */
import { getAuthTables } from "@better-auth/core/db";
import { twoFactor } from "better-auth/plugins/two-factor";

const authOptions = {
  plugins: [twoFactor({ issuer: "LLMinfo" })],
  rateLimit: {
    storage: "database" as const,
    modelName: "rateLimit",
    fields: { key: "key", count: "count", lastRequest: "lastRequest" },
  },
};

const tables = getAuthTables(authOptions as never);

function sqlType(field: { type: string; bigint?: boolean }): string {
  switch (field.type) {
    case "number":
    case "date":
      return field.bigint ? "INTEGER" : "INTEGER";
    case "boolean":
      return "INTEGER";
    default:
      return "TEXT";
  }
}

const statements: string[] = [];
for (const [key, table] of Object.entries(tables)) {
  if ((table as { disableMigrations?: boolean }).disableMigrations) continue;
  const name = (table as { modelName: string }).modelName;
  const fields = (table as { fields: Record<string, Record<string, unknown>> }).fields;

  // better-auth's own migration adds the primary key column itself, so the
  // generated DDL must do the same or the adapter reports a schema mismatch.
  const columns: string[] = ['      id TEXT PRIMARY KEY NOT NULL'];

  for (const [fieldName, field] of Object.entries(fields)) {
    const column = (field.fieldName as string) ?? fieldName;
    const parts = [`${column} ${sqlType(field as never)}`];
    if (field.required) parts.push("NOT NULL");
    if (field.unique) parts.push("UNIQUE");
    // Boolean columns are nullable with a default, matching better-auth.
    if (field.type === "boolean") parts.push("DEFAULT 0");
    if (field.references) {
      const ref = field.references as { model: string; field: string; onDelete?: string };
      parts.push(`REFERENCES "${ref.model}"(${ref.field})`);
      if (ref.onDelete) parts.push(`ON DELETE ${ref.onDelete.toUpperCase()}`);
    }
    columns.push("      " + parts.join(" "));
  }

  statements.push(`    CREATE TABLE IF NOT EXISTS "${name}" (\n${columns.join(",\n")}\n    );`);

  const indexes = (table as { indexes?: { name?: string; fields: string[]; unique?: boolean }[] }).indexes;
  for (const index of indexes ?? []) {
    const indexName = index.name ?? `${name}_${index.fields.join("_")}_idx`;
    statements.push(
      `    CREATE ${index.unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS "${indexName}" ON "${name}" (${index.fields
        .map((f) => `"${f}"`)
        .join(", ")});`,
    );
  }
}

console.log("-- Generated by scripts/gen-auth-schema.ts. Do not edit by hand.");
console.log(statements.join("\n\n"));
